import { randomUUID } from 'node:crypto';
import { createZip } from './zip.mjs';

const core = 'http://schemas.microsoft.com/3dmanufacturing/core/2015/02';
const production = 'http://schemas.microsoft.com/3dmanufacturing/production/2015/06';
const relationships = 'http://schemas.openxmlformats.org/package/2006/relationships';
const modelRelationship = 'http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel';
const header = '<?xml version="1.0" encoding="UTF-8"?>\n';
const identity = '1 0 0 0 1 0 0 0 1 0 0 0';
const matrix = '1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1';

function xml(value) {
  return String(value).replace(/[&<>"']/g, character =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' })[character]);
}

function meshXml(vertices) {
  const unique = new Map();
  const points = [];
  const indices = vertices.map(vertex => {
    const key = vertex.join(',');
    if (!unique.has(key)) {
      unique.set(key, unique.size);
      points.push(`<vertex x="${vertex[0]}" y="${vertex[1]}" z="${vertex[2]}"/>`);
    }
    return unique.get(key);
  });
  const triangles = [];
  for (let i = 0; i < indices.length; i += 3) {
    triangles.push(`<triangle v1="${indices[i]}" v2="${indices[i + 1]}" v3="${indices[i + 2]}"/>`);
  }
  return `<mesh><vertices>${points.join('')}</vertices><triangles>${triangles.join('')}</triangles></mesh>`;
}

export function createBambuProject(parts) {
  if (!Array.isArray(parts) || !parts.length) throw new Error('A 3MF project needs at least one lid part.');
  for (const part of parts) {
    if (typeof part.name !== 'string' || !part.name || !/^#[0-9A-F]{6}$/i.test(part.color)
      || !Array.isArray(part.vertices) || !part.vertices.length || part.vertices.length % 3 !== 0
      || !part.vertices.every(vertex => Array.isArray(vertex) && vertex.length === 3 && vertex.every(Number.isFinite))) {
      throw new Error('Each 3MF part needs a name, RGB hex color, and finite triangle vertices.');
    }
  }
  const colors = [...new Set(parts.map(part => part.color.toUpperCase()))];
  const extruder = part => colors.indexOf(part.color.toUpperCase()) + 1;
  const objectId = parts.length + 1;
  const minimum = [Infinity, Infinity, Infinity];
  for (const part of parts) {
    for (const vertex of part.vertices) vertex.forEach((value, axis) => { minimum[axis] = Math.min(minimum[axis], value); });
  }
  // Move the complete assembly, never individual inlays, onto the positive XY
  // quadrant and Z=0 without assuming a particular printer's bed dimensions.
  const placement = `1 0 0 0 1 0 0 0 1 ${10 - minimum[0]} ${10 - minimum[1]} ${-minimum[2]}`;
  // Bambu uses this application prefix to load project settings, rather than
  // treating the package as geometry only. Description identifies our exporter.
  const model = header + `<model unit="millimeter" xml:lang="en-US" xmlns="${core}"
 xmlns:BambuStudio="http://schemas.bambulab.com/package/2021" xmlns:p="${production}" requiredextensions="p">
<metadata name="Application">BambuStudio-02.00.00.00</metadata>
<metadata name="BambuStudio:3mfVersion">1</metadata>
<metadata name="Title">Drawer box lid</metadata>
<metadata name="Description">Generated by the openscad-drawer-box 3MF exporter</metadata>
<resources><object id="${objectId}" type="model" p:UUID="${randomUUID()}"><components>
${parts.map((part, index) => `<component objectid="${index + 1}" p:path="/3D/Objects/lid.model" p:UUID="${randomUUID()}" transform="${identity}"/>`).join('\n')}
</components></object></resources>
<build p:UUID="${randomUUID()}"><item objectid="${objectId}" p:UUID="${randomUUID()}" transform="${placement}" printable="1"/></build>
</model>`;
  const objects = header + `<model unit="millimeter" xml:lang="en-US" xmlns="${core}"><resources>
${parts.map((part, index) => `<object id="${index + 1}" type="model" name="${xml(part.name)}">${meshXml(part.vertices)}</object>`).join('\n')}
</resources><build/></model>`;
  const settings = header + `<config>
<object id="${objectId}">
<metadata key="name" value="Drawer box lid"/>
<metadata key="extruder" value="1"/>
${parts.map((part, index) => `<part id="${index + 1}" subtype="normal_part">
<metadata key="name" value="${xml(part.name)}"/>
<metadata key="extruder" value="${extruder(part)}"/>
<metadata key="matrix" value="${matrix}"/>
<mesh_stat face_count="${part.vertices.length / 3}" edges_fixed="0" degenerate_facets="0" facets_removed="0" facets_reversed="0" backwards_edges="0"/>
</part>`).join('\n')}
</object>
<plate><metadata key="plater_id" value="1"/><metadata key="plater_name" value="Lid"/>
<metadata key="locked" value="false"/>
<model_instance><metadata key="object_id" value="${objectId}"/><metadata key="instance_id" value="0"/><metadata key="identify_id" value="1"/></model_instance>
</plate><assemble/>
</config>`;
  const project = {
    version: '02.00.00.00',
    filament_colour: colors,
    filament_type: colors.map(() => 'PLA'),
    filament_diameter: colors.map(() => '1.75'),
    filament_settings_id: colors.map(() => 'Generic PLA'),
    nozzle_diameter: ['0.4'],
    printable_height: '100',
    flush_volumes_matrix: colors.flatMap((from, row) =>
      colors.map((to, column) => row === column ? '0' : '280')),
    printer_model: '',
    printer_settings_id: '',
    print_settings_id: '',
    // Bambu expects one entry for print, each filament, and printer, even when
    // no specific presets are embedded. Omitting these can crash its loader.
    inherits_group: Array(colors.length + 2).fill(''),
    different_settings_to_system: Array(colors.length + 2).fill(''),
  };
  return createZip([
    ['[Content_Types].xml', header + `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
<Default Extension="config" ContentType="application/xml"/>
<Override PartName="/Metadata/project_settings.config" ContentType="application/json"/>
</Types>`],
    ['_rels/.rels', header + `<Relationships xmlns="${relationships}"><Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="${modelRelationship}"/></Relationships>`],
    ['3D/3dmodel.model', model],
    ['3D/_rels/3dmodel.model.rels', header + `<Relationships xmlns="${relationships}"><Relationship Target="/3D/Objects/lid.model" Id="rel-1" Type="${modelRelationship}"/></Relationships>`],
    ['3D/Objects/lid.model', objects],
    ['Metadata/model_settings.config', settings],
    ['Metadata/project_settings.config', JSON.stringify(project, null, 2)],
  ]);
}
