import { randomUUID } from 'node:crypto';
import { createZip } from './zip.mjs';

const core = 'http://schemas.microsoft.com/3dmanufacturing/core/2015/02';
const production = 'http://schemas.microsoft.com/3dmanufacturing/production/2015/06';
const relationships = 'http://schemas.openxmlformats.org/package/2006/relationships';
const modelRelationship = 'http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel';
const header = '<?xml version="1.0" encoding="UTF-8"?>\n';
const identity = '1 0 0 0 1 0 0 0 1 0 0 0';
const matrix = '1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1';

function xml(value) {
  return String(value).replace(/[&<>"']/g, character =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' })[character]);
}

function meshXml(vertices) {
  const unique = new Map();
  const points = [];
  const indices = vertices.map(vertex => {
    const key = vertex.join(',');
    if (!unique.has(key)) {
      unique.set(key, unique.size);
      points.push(`<vertex x="${vertex[0]}" y="${vertex[1]}" z="${vertex[2]}"/>`);
    }
    return unique.get(key);
  });
  const triangles = [];
  for (let i = 0; i < indices.length; i += 3) {
    triangles.push(`<triangle v1="${indices[i]}" v2="${indices[i + 1]}" v3="${indices[i + 2]}"/>`);
  }
  return `<mesh><vertices>${points.join('')}</vertices><triangles>${triangles.join('')}</triangles></mesh>`;
}

export function createBambuProject(parts, { box } = {}) {
  if (!Array.isArray(parts) || !parts.length) throw new Error('A 3MF project needs at least one lid part.');
  const allParts = box ? [box, ...parts] : parts;
  for (const part of allParts) {
    if (typeof part.name !== 'string' || !part.name || !/^#[0-9A-F]{6}$/i.test(part.color)
      || !Array.isArray(part.vertices) || !part.vertices.length || part.vertices.length % 3 !== 0
      || !part.vertices.every(vertex => Array.isArray(vertex) && vertex.length === 3 && vertex.every(Number.isFinite))) {
      throw new Error('Each 3MF part needs a name, RGB hex color, and finite triangle vertices.');
    }
  }
  const meshParts = allParts.map((part, index) => ({ ...part, id: index + 1 }));
  const groups = box
    ? [{ name: 'Box', parts: meshParts.slice(0, 1) }, { name: 'Lid', parts: meshParts.slice(1) }]
    : [{ name: 'Lid', parts: meshParts }];
  for (const [index, group] of groups.entries()) {
    group.id = meshParts.length + index + 1;
    group.minimum = [Infinity, Infinity, Infinity];
    group.maximum = [-Infinity, -Infinity, -Infinity];
    for (const part of group.parts) {
      for (const vertex of part.vertices) {
        vertex.forEach((value, axis) => {
          group.minimum[axis] = Math.min(group.minimum[axis], value);
          group.maximum[axis] = Math.max(group.maximum[axis], value);
        });
      }
    }
  }
  const bedWidth = Math.max(200, ...groups.map(group => Math.ceil(group.maximum[0] - group.minimum[0]) + 20));
  const bedDepth = Math.max(200, ...groups.map(group => Math.ceil(group.maximum[1] - group.minimum[1]) + 20));
  const bedHeight = Math.max(100, ...groups.map(group => Math.ceil(group.maximum[2] - group.minimum[2]) + 10));
  const colors = [...new Set(meshParts.map(part => part.color.toUpperCase()))];
  const extruder = part => colors.indexOf(part.color.toUpperCase()) + 1;
  // Bambu lays two plates side-by-side, separated by 20% of the bed width.
  // Apply placement to each whole object; lid inlays keep their shared coordinates.
  const placement = (group, plate) =>
    `1 0 0 0 1 0 0 0 1 ${plate * bedWidth * 1.2 + 10 - group.minimum[0]} ${10 - group.minimum[1]} ${-group.minimum[2]}`;
  const meshPath = box ? '3D/Objects/parts.model' : '3D/Objects/lid.model';
  // Bambu uses this application prefix to load project settings, rather than
  // treating the package as geometry only. Description identifies our exporter.
  const model = header + `<model unit="millimeter" xml:lang="en-US" xmlns="${core}"
 xmlns:BambuStudio="http://schemas.bambulab.com/package/2021" xmlns:p="${production}" requiredextensions="p">
<metadata name="Application">BambuStudio-02.00.00.00</metadata>
<metadata name="BambuStudio:3mfVersion">1</metadata>
<metadata name="Title">${box ? 'Drawer box and lid' : 'Drawer box lid'}</metadata>
<metadata name="Description">Generated by the openscad-drawer-box 3MF exporter</metadata>
<resources>${groups.map(group => `<object id="${group.id}" type="model" p:UUID="${randomUUID()}"><components>
${group.parts.map(part => `<component objectid="${part.id}" p:path="/${meshPath}" p:UUID="${randomUUID()}" transform="${identity}"/>`).join('\n')}
</components></object>`).join('\n')}</resources>
<build p:UUID="${randomUUID()}">${groups.map((group, plate) =>
    `<item objectid="${group.id}" p:UUID="${randomUUID()}" transform="${placement(group, plate)}" printable="1"/>`).join('\n')}</build>
</model>`;
  const objects = header + `<model unit="millimeter" xml:lang="en-US" xmlns="${core}"><resources>
${meshParts.map(part => `<object id="${part.id}" type="model" name="${xml(part.name)}">${meshXml(part.vertices)}</object>`).join('\n')}
</resources><build/></model>`;
  const settings = header + `<config>
${groups.map(group => `<object id="${group.id}">
<metadata key="name" value="${group.name === 'Box' ? 'Drawer box' : 'Drawer box lid'}"/>
<metadata key="extruder" value="${extruder(group.parts[0])}"/>
${group.parts.map(part => `<part id="${part.id}" subtype="normal_part">
<metadata key="name" value="${xml(part.name)}"/>
<metadata key="extruder" value="${extruder(part)}"/>
<metadata key="matrix" value="${matrix}"/>
<mesh_stat face_count="${part.vertices.length / 3}" edges_fixed="0" degenerate_facets="0" facets_removed="0" facets_reversed="0" backwards_edges="0"/>
</part>`).join('\n')}
</object>`).join('\n')}
${groups.map((group, plate) => `<plate><metadata key="plater_id" value="${plate + 1}"/><metadata key="plater_name" value="${group.name}"/>
<metadata key="locked" value="false"/>
<model_instance><metadata key="object_id" value="${group.id}"/><metadata key="instance_id" value="0"/><metadata key="identify_id" value="${plate + 1}"/></model_instance>
</plate>`).join('\n')}<assemble/>
</config>`;
  const project = {
    version: '02.00.00.00',
    filament_colour: colors,
    filament_type: colors.map(() => 'PLA'),
    filament_diameter: colors.map(() => '1.75'),
    filament_settings_id: colors.map(() => 'Generic PLA'),
    nozzle_diameter: ['0.4'],
    printable_height: String(bedHeight),
    ...(box ? { printable_area: ['0x0', `${bedWidth}x0`, `${bedWidth}x${bedDepth}`, `0x${bedDepth}`] } : {}),
    flush_volumes_matrix: colors.flatMap((from, row) =>
      colors.map((to, column) => row === column ? '0' : '280')),
    printer_model: '',
    printer_settings_id: '',
    print_settings_id: '',
    // Bambu expects one entry for print, each filament, and printer, even when
    // no specific presets are embedded. Omitting these can crash its loader.
    inherits_group: Array(colors.length + 2).fill(''),
    different_settings_to_system: Array(colors.length + 2).fill(''),
  };
  return createZip([
    ['[Content_Types].xml', header + `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
<Default Extension="config" ContentType="application/xml"/>
<Override PartName="/Metadata/project_settings.config" ContentType="application/json"/>
</Types>`],
    ['_rels/.rels', header + `<Relationships xmlns="${relationships}"><Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="${modelRelationship}"/></Relationships>`],
    ['3D/3dmodel.model', model],
    ['3D/_rels/3dmodel.model.rels', header + `<Relationships xmlns="${relationships}"><Relationship Target="/${meshPath}" Id="rel-1" Type="${modelRelationship}"/></Relationships>`],
    [meshPath, objects],
    ['Metadata/model_settings.config', settings],
    ['Metadata/project_settings.config', JSON.stringify(project, null, 2)],
  ]);
}
